import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "./_components/ThemeProvider";
import { ModalProvider } from "@/providers/modal-provider";
import { SessionProvider } from "next-auth/react";
import ReactQueryprovider from "@/providers/ReactQueryprovidet";
import { extractRouterConfig } from "uploadthing/server";
import { fileRouter } from "@/app/api/uploadthing/core";

import { Pen } from "lucide-react";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import Providers from "@/components/ui/ProgressBar";
export const metadata: Metadata = {
  title: "X",
  description: "Generated by create next app",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(`${geistSans.variable} ${geistMono.variable} antialiased `)}
      >
        <ReactQueryprovider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <SessionProvider>
              <NextSSRPlugin
                routerConfig={extractRouterConfig(fileRouter)}
              />
              <Providers>
                {children}
              </Providers>

              <Toaster />
              <ModalProvider />
            </SessionProvider>
          </ThemeProvider>

        </ReactQueryprovider>


      </body>
    </html>
  );
}
